/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-03-26 01:56:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.pizza;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class pizzaOrderForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>피자 주문 페이지</h1>\r\n");
      out.write("\r\n");
      out.write("    <h2>오늘의 날짜</h2>\r\n");
      out.write("    ");

        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일"); //
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h4>");
      out.print(sdf.format(today));
      out.write("</h4>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    <!--\r\n");
      out.write("        주문자정보, 주문정보 입력받아서\r\n");
      out.write("        서버에 결제 요청(servlet에 전달)\r\n");
      out.write("        controller -> pizzaServlet.java\r\n");
      out.write("        응답을 위한 jsp페이지가 필요\r\n");
      out.write("        pizza > pizzaPayment.jsp\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("    <form action=\"/jsp/confirmPizza.do\" method=\"GET\">\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>주문자 정보</legend>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>이름</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"userName\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>전화번호</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"phone\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>주소</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"address\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>요청메세지</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"message\" required> <textarea name=\"\" id=\"\" cols=\"30\" rows=\"10\"></textarea></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    <br>\r\n");
      out.write("    <fieldset>\r\n");
      out.write("        <legend>주문정보</legend>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>피자</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select name=\"pizza\">\r\n");
      out.write("                            <option>콤비네이션</option>\r\n");
      out.write("                            <option>치즈피자</option>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <option>포테이토피자</option>\r\n");
      out.write("                            <option>고구마피자</option>\r\n");
      out.write("                            <option>하와이안피자</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>토핑</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"고구마무스\">고구마무스\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"치즈크러스트\">치즈크러스트\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"치즈바이트\">치즈바이트\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"베이컨\">베이컨\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"옥수수\">옥수수\r\n");
      out.write("                        <input type=\"checkbox\" name=\"topping\" value=\"파인애플\">파인애플\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>사이드</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"콜라\">콜라\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"사이다\">사이다\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"피클\">피클\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"핫소스\">핫소스\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"파마산\">파마산\r\n");
      out.write("                        <input type=\"checkbox\" name=\"side\" value=\"갈릭\">갈릭\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>결제방식\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"radio\" name=\"payment\" value=\"card\" checked> 카드결제\r\n");
      out.write("                            <input type=\"radio\" name=\"payment\" value=\"cash\" > 현금결제\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table> \r\n");
      out.write("    </fieldset>\r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"submit\" value=\"결제\">\r\n");
      out.write("    <input type=\"reset\" value=\"초기화\">\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
